"""Add email and phone number as optional fields in user

Revision ID: 750e38eb858a
Revises: f4781dd2f838
Create Date: 2024-12-22 17:07:36.440934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750e38eb858a'
down_revision: Union[str, None] = 'f4781dd2f838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_oauth_tokens', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user_oauth_tokens', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_oauth_tokens', 'email')
    op.drop_column('user_oauth_tokens', 'phone_number')
    # ### end Alembic commands ###
