"""Create UserOauth table

Revision ID: f4781dd2f838
Revises: b500c2a71ae2
Create Date: 2024-12-22 16:03:37.184287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4781dd2f838'
down_revision: Union[str, None] = 'b500c2a71ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_tokens_id'), 'user_oauth_tokens', ['id'], unique=False)
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_user_oauth_tokens_id'), table_name='user_oauth_tokens')
    op.drop_table('user_oauth_tokens')
    # ### end Alembic commands ###
